---
- name: Install Apache
  hosts: node1.test
  become: yes

  tasks:
    - name: Install Apache
      apt: 
        name: apache2 
        state: present
    

    - name: Copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: apache2.conf
          dest: /etc/apache2/apache2.conf
        - src: 000-default.conf
          dest: /etc/apache2/sites-available/000-default.conf

    - name: Ensure Apache is started now and at boot
      service:
        name: apache2 
        state: started
        enabled: true

