---
- name: Configure NTP on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Ensure NTP package is installed
      apt:
        name: ntp
        state: present
        update_cache: yes

    - name: Ensure NTP service is started and enabled
      service:
        name: ntp
        state: started
        enabled: yes

