---
- name: Install Apache
  hosts: apache
  become: true

  vars:
    proxy_vars:
      http_proxy: http://example-proxy:80/
      https_proxy: https://example-proxy:80/

  vars_files:
    - vars/apache_default.yml

  handlers:
    - import_tasks: handlers/apache.yml

  tasks:
    - import_tasks: tasks/apache.yml